package message;

public enum MessageType {
	// Messages de la partie
	DEBUT_PARTIE, FIN_PARTIE, DEBUT_TOUR, FIN_TOUR, DEBUT_TOUR_JOUEUR, FIN_TOUR_JOUEUR, RESULTAT_JOUR, RESULTAT_NEANT, RESULTAT_NUIT,

	// Messages des cartes
	TAS_MELANGE, CARTE_EXEC, CARTE_SET_CIBLE, CARTE_SET_POSITION_MAIN_JOUEUR, CARTE_SET_POSITION_MILIEU, CARTE_SET_POSITION_DEVANT_JOUEUR,

	// Messages des joueurs
	JOUEUR_DEBUT_TOUR, JOUEUR_FIN_TOUR, JOUEUR_PIOCHE_CARTE, JOUEUR_DEFAUSSE_CARTE, JOUEUR_POSE_CROYANT, JOUEUR_POSE_GUIDE, JOUEUR_ACTIVE_DEUSEX, JOUEUR_ACTIVE_CROYANT, JOUEUR_ACTIVE_GUIDE, JOUEUR_ACTIVE_DIVINITE, JOUEUR_GAGNE_PRIERES,
}
 